services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_DIR}:/config
      - ${DATA_DIR}:/data
    networks:
      - media_network
      - proxy_network

#################################
# NETWORK
#################################
networks:
  media_network:
    name: media_network
    external: true
  proxy_network:
    name: proxy_network
    external: true
